apiVersion: batch/v1
kind: Job
metadata:
  name: django-migrate
  namespace: default
spec:
  ttlSecondsAfterFinished: 5
  template:
    spec:
      containers:
      - name: django-test-clearsessions
        image: django_app:latest
        imagePullPolicy: IfNotPresent
        env:
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: django-k8s-env
              key: SECRET_KEY
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: django-k8s-env
              key: DATABASE_URL
        - name: ALLOWED_HOSTS
          valueFrom:
            secretKeyRef:
              name: django-k8s-env
              key: ALLOWED_HOSTS
        - name: DEBUG
          valueFrom:
            secretKeyRef:
              name: django-k8s-env
              key: DEBUG
        command: ["python"]
        args: ["manage.py", "migrate"]
      restartPolicy: OnFailure
  backoffLimit: 4
